"""Shared persisted-chat contract constants."""

MAX_IDEMPOTENCY_KEY_LENGTH = 255
USER_MESSAGE_IDEMPOTENCY_PREFIX = "user:"
CHAT_CLIENT_MESSAGE_ID_MAX_CHARS = MAX_IDEMPOTENCY_KEY_LENGTH - len(USER_MESSAGE_IDEMPOTENCY_PREFIX)
